export const ADD_DEVICE_FAILED = 'ADD_DEVICE_FAILED';
export const DEVICE_DELETED = 'DEVICE_DELETED';
export const DEVICE_DELETE_FAILED = 'DEVICE_DELETE_FAILED';
export const DEVICE_UPDATED = 'DEVICE_UPDATED';
export const DEVICE_UPDATE_FAILED = 'DEVICE_UPDATE_FAILED';