export const ADD_DEVICE = "ADD_DEVICE";
export const SET_DEVICES = "SET_DEVICES";
export const TURN_OFF_ALL_DEVICES = "TURN_ON_OFF_ALL_DEVICES";
export const TURN_ON_OFF_DEVICE = "TURN_ON_OFF_DEVICE";
export const UPDATE_DEVICE = "UPDATE_DEVICE";
export const REMOVE_DEVICE = "REMOVE_DEVICE";
export const SET_CURRENT_PAGE = "SET_CURRENT_PAGE";

export const FETCH_DEVICES = "FETCH_DEVICES";

export const SET_DEVICES_TYPE = "SET_DEVICES_TYPE"
export const SET_TOTAL_ITEMS = "SET_TOTAL_ITEMS";